In [2]:
import torch
#check GPU availability
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")


Is the GPU available? False


In [3]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

Device cpu


In [4]:
#Various ways you can perform tensor addition
a = torch.rand(2,2)
print(a)
b = torch.rand(2,2)
c = a + b
d = torch.add(a,b)
#For in-place addition
print(d)

tensor([[0.6187, 0.8142],
        [0.1981, 0.8475]])
tensor([[1.0565, 1.2666],
        [0.5940, 1.2166]])


In [5]:
a.add_(5)

tensor([[5.6187, 5.8142],
        [5.1981, 5.8475]])

In [6]:
print(a)
print(a*b)
print(a.mul(b))

tensor([[5.6187, 5.8142],
        [5.1981, 5.8475]])
tensor([[2.4599, 2.6308],
        [2.0583, 2.1582]])
tensor([[2.4599, 2.6308],
        [2.0583, 2.1582]])


In [7]:
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)
print(a.size)
a.matmul(b)

<built-in method size of Tensor object at 0x000001C392B537C0>


tensor([[2467.3354, 2519.4539, 2490.2942,  ..., 2537.3083, 2518.6099,
         2482.7126],
        [2463.6174, 2512.8564, 2500.3770,  ..., 2530.6787, 2540.0569,
         2469.7932],
        [2458.5974, 2488.6399, 2495.5125,  ..., 2522.6743, 2522.5999,
         2466.6306],
        ...,
        [2510.9592, 2546.8135, 2528.0874,  ..., 2548.4326, 2557.8257,
         2505.0859],
        [2463.1848, 2487.4351, 2491.3108,  ..., 2518.6421, 2530.0337,
         2458.3274],
        [2448.6309, 2488.9424, 2488.0315,  ..., 2501.9126, 2524.5276,
         2450.4771]])

In [8]:
import numpy as np
l=[2,3,4,5]
a=np.array(l)

In [9]:
arr=torch.from_numpy(a)
print(arr)

tensor([2, 3, 4, 5], dtype=torch.int32)


In [10]:
f=torch.zeros(2,3,dtype=torch.float64)
print(f)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [11]:
a=torch.tensor([5,6,7],dtype=torch.float)
b=torch.tensor([1,2,3],dtype=torch.float)
print(a+b)

tensor([ 6.,  8., 10.])


In [12]:
torch.add(b,a,out=c)
print(c)

tensor([ 6.,  8., 10.])


C:\Users\ponku\AppData\Local\Temp/ipykernel_15884/571966660.py:1: UserWarning: An output with one or more elements was resized since it had shape [2, 2], which does not match the required output shape [3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:24.)
  torch.add(b,a,out=c)


In [13]:
torch.add(a,b).sum()

tensor(24.)

In [14]:
a=torch.tensor([4,5])
b=torch.tensor([2,3])
a.mul(b)

tensor([ 8, 15])

In [15]:
a.dot(b)

tensor(23)

In [16]:
import torch
  
# creating a tensor with random 
# values of dimension 3 X 5 X 2
input_var = torch.randn(3, 5, 2)
  
# print size
print(input_var.size())
  
print(input_var)
  
# dimensions permuted
input_var = input_var.permute(2, 0, 1)
  
# print size
print(input_var.size())
  
print(input_var)

torch.Size([3, 5, 2])
tensor([[[-1.5445,  1.6452],
         [ 0.4181, -0.1678],
         [ 1.2562,  0.3379],
         [-0.5347, -1.5868],
         [ 0.8426, -0.6028]],

        [[ 0.5956,  0.9728],
         [-1.7924,  1.2561],
         [ 1.4748, -2.4358],
         [-0.8120,  1.4552],
         [ 1.2839, -0.5423]],

        [[-0.5663,  0.4954],
         [-0.0252,  0.1390],
         [ 0.6573, -0.1574],
         [ 0.3083, -1.9023],
         [-1.3625,  0.1542]]])
torch.Size([2, 3, 5])
tensor([[[-1.5445,  0.4181,  1.2562, -0.5347,  0.8426],
         [ 0.5956, -1.7924,  1.4748, -0.8120,  1.2839],
         [-0.5663, -0.0252,  0.6573,  0.3083, -1.3625]],

        [[ 1.6452, -0.1678,  0.3379, -1.5868, -0.6028],
         [ 0.9728,  1.2561, -2.4358,  1.4552, -0.5423],
         [ 0.4954,  0.1390, -0.1574, -1.9023,  0.1542]]])


In [24]:
a1=torch.tensor([[5,9],[2,2]],dtype=torch.float32)
a2=torch.tensor([[6,7],[9,10]],dtype=torch.float32)
C=torch.zeros((2,2),dtype=torch.float32)
for i in range(2):
    v=0
    for j in range(2):
        v=torch.dot(a1[i,:],a2[:,j])
        print("a:**",a1[i,:])
        print("b:**",a2[:,j])
        C[i][j]=v
print(C)
print(torch.matmul(a1,a2))
print(a1.mul(a2))
print(torch.inverse(C))
C=C.numpy()
print(C)

a:** tensor([5., 9.])
b:** tensor([6., 9.])
a:** tensor([5., 9.])
b:** tensor([ 7., 10.])
a:** tensor([2., 2.])
b:** tensor([6., 9.])
a:** tensor([2., 2.])
b:** tensor([ 7., 10.])
tensor([[111., 125.],
        [ 30.,  34.]])
tensor([[111., 125.],
        [ 30.,  34.]])
tensor([[30., 63.],
        [18., 20.]])
tensor([[ 1.4167, -5.2083],
        [-1.2500,  4.6250]])
[[111. 125.]
 [ 30.  34.]]


In [42]:
N=3
inv = [None for _ in range(N)]
def getCofactor(A, temp, p, q, n):
    i = 0
    j = 0 
    for row in range(n):
 
        for col in range(n):
            if (row != p and col != q):
 
                temp[i][j] = A[row][col]
                j += 1
                if (j == n - 1):
                    j = 0
                    i += 1
def determinant(A, n):
    D = 0
    if (n == 1):
        return A[0][0]
    temp = [] 
    for i in range(N):
        temp.append([None for _ in range(N)])
    sign = 1  
    for f in range(n):
        getCofactor(A, temp, 0, f, n)
        D += sign * A[0][f] * determinant(temp, n - 1)
        sign = -sign
 
    return D
def adjoint(A, adj):
    if (N == 1):
        adj[0][0] = 1
        return
    sign = 1
    temp = []
    for i in range(N):
        temp.append([None for _ in range(N)])
    for i in range(N):
        for j in range(N):
            # Get cofactor of A[i][j]
            getCofactor(A, temp, i, j, N)
            sign = [1, -1][(i + j) % 2]
            adj[j][i] = (sign)*(determinant(temp, N-1))
def inverse(A, inverse):
    det = determinant(A, N)
    if (det == 0):
        print("Singular matrix, can't find its inverse")
        return False
    adj = []
    for i in range(N):
        adj.append([None for _ in range(N)])
    adjoint(A, adj)
    for i in range(N):
        for j in range(N):
            inverse[i][j] = adj[i][j] / det
    return True
def displays(A):
    for i in range(N):
        for j in range(N):
            print(round(A[i][j], 6), end=" ")
        print()
for i in range(N):
    inv[i] = [None for _ in range(N)]
A=[[3,4,5],[1,2,1],[3,2,1]]
inverse(A,inv)
print(inv)
displays(inv)

[[-0.0, -0.5, 0.5], [-0.16666666666666666, 1.0, -0.16666666666666666], [0.3333333333333333, -0.5, -0.16666666666666666]]
-0.0 -0.5 0.5 
-0.166667 1.0 -0.166667 
0.333333 -0.5 -0.166667 
